version: '3'

services: 
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
    volumes: 
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - postgres_db

  billingapp-back:
    build:
      context: ./java
      args: 
        - JAR_FILE=*.jar
        - DB_PASSWORD=qwerty
    container_name: billingapp-back
    environment:
      - JAVA_OPTS=
        - Xms256M
        - Xms256M
    depends_on:
      - postgres_db
    ports:
      - 8080:8080

  services:
    build:
      context: ./angular
    container_name: billingapp-front
    depends_on:
      - billingapp-back
    ports:
      - 3000:3000